// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public class Card
	{
		public enum ServantType
		{
			Saber,
			Archer,
			Lancer,
			Rider,
			Assassin,
			Caster,
			Berserker,

			Size
		}

		private int 		power;
		private int 		hp;
		private ServantType type;
		private string 		name;
		
		public Card(string n, ServantType t, int p, int h)
		{
			power = p;
			hp = h;
			type = t;
			name = n;
		}

		public void SustainHit(int damage)
		{
			int remaininghp = hp - damage;
			if (remaininghp >= 0)
				hp = remaininghp;
			else
				hp = 0;
		}

		public ServantType GetCardType()
		{
			return type;
		}

		public string GetName()
		{
			return name;
		}

		public int GetHitPoints()
		{
			return hp;
		}

		public int GetPower()
		{
			return power;
		}
	}
}

